spring:
  datasource:
    url: jdbc:mysql://localhost:3308/cardsdb
    username: root
    password: "{cipher}ea314ecf62ee347afb6518558385e83de91d6d18a32aa20fba02f81e45d505c3"
    driver-class-name: com.mysql.cj.jdbc.Driver

cards:
  message: "Welcome to EazyBank cards related QA APIs "
  contactDetails:
    name: "Cherryl Pankaj - QA Lead"
    email: "cherryl@eazybank.com"
  onCallSupport:
    - (310) 875-4367
    - (201) 236-1267